### ISSUE TITLE
Can you upload the pre-processed model? As my English is poor, it is difficult for me to understand these operations

### ISSUE THREAD

**Issue by SuperCarryFu** [huitailangyz/MGAA#2]

**Comment by huitailangyz** [comment]
Thank you for your interest in our work. We have provided the download link of all pretrained models, and also the process script for the model. You just need to run the code for adaptively changing the name of variables. Based on feedback from others, the preprocessing code provided in `misc.py` is valid.


Translation for CHINESE:
感谢您对我们工作的关注。我们已经提供了所有预训练模型的下载链接以及所有对于预训练模型的处理代码。您只需要运行这些文件来对预训练模型中的变量名进行重命名即可。根据其他人的反馈，我们提供的预处理代码`misc.py`是有效的

**Comment by SuperCarryFu** [comment]
Thank you. I will continue to try and contact you if I have any questions. Thanks again



---Original---
From: ***@***.***&gt;
Date: Wed, Mar 9, 2022 22:37 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [huitailangyz/MGAA] Can you upload the pre-processed model? As my English is poor, it is difficult for me to understand these operations (Issue #2)




 
Thank you for your interest in our work. We have provided the download link of all pretrained models, and also the process script for the model. You just need to run the code for adaptively changing the name of variables. Based on feedback from others, the preprocessing code provided in misc.py is valid.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SuperCarryFu** [comment]
The code doesn't seem to use the GPU?

**Comment by huitailangyz** [comment]
The command for running the shell script contains the GPU used, \ie, `CUDA_VISIBLE_DEVICES=X bash run_attack.sh`

**Comment by SuperCarryFu** [comment]
Thank you. The problem has been solved,
When I use the latest version of Conda
conda install tensorflow-gpu=1.9.0 NO
pip install tensorflow-gpu=1.9.0 yes
